spring.datasource.url=jdbc:mysql://localhost:3306/tastytalks
spring.datasource.username=root
spring.datasource.password=admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
jwt.secret=ChangeThisSecretForProd
jwt.expiration-ms=86400000